import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - therealJMT",
    template: "%s | therealJMT",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{
          backgroundColor: 'darkblue',
          color: 'white',
          padding: '1rem',
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer
        style={{
          backgroundColor: 'rebeccapurple',
          color: 'white',
          padding: '1rem',
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
